spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kasir?useSSL=false
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
  liquibase:
    change-log: classpath:/database/changelog/changelog.xml

server:
  port: 8888
  servlet:
    context-path: /marketplace